micronaut:
  application:
    name: book-management-system

datasources:
  default:
    url: jdbc:h2:mem:app-dev;DB_CLOSE_ON_EXIT=FALSE
    username: app
    password: app
    driverClassName: org.h2.Driver
    dialect: h2
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
      url: jdbc:h2:mem:app-dev;DB_CLOSE_ON_EXIT=FALSE
      username: app
      password: app
      driverClassName: org.h2.Driver
      dialect: h2

endpoints:
  flyway:
    enabled: true
    sensitive: false
